"""regenerate migrations

Revision ID: 4986f54cff13
Revises:
Create Date: 2026-04-17 14:53:21.056944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4986f54cff13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    op.create_table('alert_resolution_status',
    sa.Column('resolution_status_id', sa.Integer(), nullable=False),
    sa.Column('resolution_status_name', sa.Text(), nullable=False),
    sa.Column('resolution_status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('resolution_status_id'),
    sa.UniqueConstraint('resolution_status_name')
    )
    op.create_table('alert_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.Text(), nullable=False),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('analysis_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_type',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=155), nullable=True),
    sa.Column('asset_description', sa.String(length=255), nullable=True),
    sa.Column('asset_icon_not_compromised', sa.String(length=255), nullable=True),
    sa.Column('asset_icon_compromised', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('case_state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.Text(), nullable=False),
    sa.Column('state_description', sa.Text(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('custom_attribute',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_display_name', sa.Text(), nullable=True),
    sa.Column('attribute_description', sa.Text(), nullable=True),
    sa.Column('attribute_for', sa.Text(), nullable=True),
    sa.Column('attribute_content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_table('event_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('group_permissions', sa.BigInteger(), nullable=False),
    sa.Column('group_auto_follow', sa.Boolean(), nullable=False),
    sa.Column('group_auto_follow_access_level', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name'),
    sa.UniqueConstraint('group_uuid')
    )
    op.create_table('ioc_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.Text(), nullable=True),
    sa.Column('type_description', sa.Text(), nullable=True),
    sa.Column('type_taxonomy', sa.Text(), nullable=True),
    sa.Column('type_validation_regex', sa.Text(), nullable=True),
    sa.Column('type_validation_expect', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('iris_hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hook_name', sa.Text(), nullable=True),
    sa.Column('hook_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organisations',
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('org_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_name', sa.Text(), nullable=False),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.Column('org_url', sa.Text(), nullable=True),
    sa.Column('org_logo', sa.Text(), nullable=True),
    sa.Column('org_email', sa.Text(), nullable=True),
    sa.Column('org_nationality', sa.Text(), nullable=True),
    sa.Column('org_sector', sa.Text(), nullable=True),
    sa.Column('org_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('org_name'),
    sa.UniqueConstraint('org_uuid')
    )
    op.create_table('os_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('report_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('https_proxy', sa.Text(), nullable=True),
    sa.Column('http_proxy', sa.Text(), nullable=True),
    sa.Column('prevent_post_mod_repush', sa.Boolean(), nullable=True),
    sa.Column('prevent_post_objects_repush', sa.Boolean(), nullable=True),
    sa.Column('has_updates_available', sa.Boolean(), nullable=True),
    sa.Column('enable_updates_check', sa.Boolean(), nullable=True),
    sa.Column('password_policy_min_length', sa.Integer(), nullable=True),
    sa.Column('password_policy_upper_case', sa.Boolean(), nullable=True),
    sa.Column('password_policy_lower_case', sa.Boolean(), nullable=True),
    sa.Column('password_policy_digit', sa.Boolean(), nullable=True),
    sa.Column('password_policy_special_chars', sa.Text(), nullable=True),
    sa.Column('enforce_mfa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('severities',
    sa.Column('severity_id', sa.Integer(), nullable=False),
    sa.Column('severity_name', sa.Text(), nullable=False),
    sa.Column('severity_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('severity_id'),
    sa.UniqueConstraint('severity_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag_title', sa.Text(), nullable=True),
    sa.Column('tag_creation_date', sa.DateTime(), nullable=True),
    sa.Column('tag_namespace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_title')
    )
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.Text(), nullable=True),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.Column('status_bscolor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tlp',
    sa.Column('tlp_id', sa.Integer(), nullable=False),
    sa.Column('tlp_name', sa.Text(), nullable=True),
    sa.Column('tlp_bscolor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tlp_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('ctx_human_case', sa.String(length=256), nullable=True),
    sa.Column('ctx_case', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('in_dark_mode', sa.Boolean(), nullable=True),
    sa.Column('has_mini_sidebar', sa.Boolean(), nullable=True),
    sa.Column('has_deletion_confirmation', sa.Boolean(), nullable=True),
    sa.Column('is_service_account', sa.Boolean(), nullable=True),
    sa.Column('mfa_secrets', sa.Text(), nullable=True),
    sa.Column('webauthn_credentials', sa.JSON(), nullable=True),
    sa.Column('mfa_setup_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('user'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('case_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('name_expanded', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title_prefix', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('note_directories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_template_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('internal_reference', sa.String(), nullable=True),
    sa.Column('naming_format', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('report_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_reference')
    )
    op.create_table('client',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sla', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('evidence_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_title', sa.Text(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_tags', sa.Text(), nullable=True),
    sa.Column('task_open_date', sa.DateTime(), nullable=True),
    sa.Column('task_close_date', sa.DateTime(), nullable=True),
    sa.Column('task_last_update', sa.DateTime(), nullable=True),
    sa.Column('task_userid_open', sa.BigInteger(), nullable=True),
    sa.Column('task_userid_close', sa.BigInteger(), nullable=True),
    sa.Column('task_userid_update', sa.BigInteger(), nullable=True),
    sa.Column('task_assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('task_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_status_id'], ['task_status.id'], ),
    sa.ForeignKeyConstraint(['task_userid_close'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_userid_open'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_userid_update'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc',
    sa.Column('ioc_id', sa.BigInteger(), nullable=False),
    sa.Column('ioc_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ioc_value', sa.Text(), nullable=True),
    sa.Column('ioc_type_id', sa.Integer(), nullable=True),
    sa.Column('ioc_description', sa.Text(), nullable=True),
    sa.Column('ioc_tags', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('ioc_misp', sa.Text(), nullable=True),
    sa.Column('ioc_tlp_id', sa.Integer(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ioc_enrichment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ioc_tlp_id'], ['tlp.tlp_id'], ),
    sa.ForeignKeyConstraint(['ioc_type_id'], ['ioc_type.type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ioc_id')
    )
    op.create_table('iris_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.BigInteger(), nullable=False),
    sa.Column('module_human_name', sa.Text(), nullable=True),
    sa.Column('module_name', sa.Text(), nullable=True),
    sa.Column('module_description', sa.Text(), nullable=True),
    sa.Column('module_version', sa.Text(), nullable=True),
    sa.Column('interface_version', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_pipeline', sa.Boolean(), nullable=True),
    sa.Column('pipeline_args', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('module_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('module_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_filters',
    sa.Column('filter_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('filter_name', sa.Text(), nullable=False),
    sa.Column('filter_description', sa.Text(), nullable=True),
    sa.Column('filter_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_is_private', sa.Boolean(), nullable=False),
    sa.Column('filter_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_organisation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary_org', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_title', sa.Text(), nullable=False),
    sa.Column('alert_description', sa.Text(), nullable=True),
    sa.Column('alert_source', sa.Text(), nullable=True),
    sa.Column('alert_source_ref', sa.Text(), nullable=True),
    sa.Column('alert_source_link', sa.Text(), nullable=True),
    sa.Column('alert_source_content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_severity_id', sa.Integer(), nullable=False),
    sa.Column('alert_status_id', sa.Integer(), nullable=False),
    sa.Column('alert_context', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_source_event_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_note', sa.Text(), nullable=True),
    sa.Column('alert_tags', sa.Text(), nullable=True),
    sa.Column('alert_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_classification_id', sa.Integer(), nullable=True),
    sa.Column('alert_resolution_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_classification_id'], ['case_classification.id'], ),
    sa.ForeignKeyConstraint(['alert_customer_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['alert_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['alert_resolution_status_id'], ['alert_resolution_status.resolution_status_id'], ),
    sa.ForeignKeyConstraint(['alert_severity_id'], ['severities.severity_id'], ),
    sa.ForeignKeyConstraint(['alert_status_id'], ['alert_status.status_id'], ),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('alert_uuid')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('soc_id', sa.String(length=256), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('initial_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closing_note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('case_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('review_status_id', sa.Integer(), nullable=True),
    sa.Column('severity_id', sa.Integer(), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('local_timezone', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['case_classification.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_status_id'], ['review_status.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['severity_id'], ['severities.severity_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['case_state.state_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('contact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_role', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('contact_work_phone', sa.Text(), nullable=True),
    sa.Column('contact_mobile_phone', sa.Text(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iris_module_hooks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('hook_id', sa.Integer(), nullable=False),
    sa.Column('is_manual_hook', sa.Boolean(), nullable=True),
    sa.Column('manual_hook_ui_name', sa.Text(), nullable=True),
    sa.Column('retry_on_fail', sa.Boolean(), nullable=True),
    sa.Column('max_retry', sa.Integer(), nullable=True),
    sa.Column('run_asynchronously', sa.Boolean(), nullable=True),
    sa.Column('wait_till_return', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hook_id'], ['iris_hooks.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['iris_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('access_level', sa.BigInteger(), nullable=False),
    sa.Column('allow_alerts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_case_association',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'case_id')
    )
    op.create_index(op.f('ix_alert_case_association_case_id'), 'alert_case_association', ['case_id'], unique=False)
    op.create_table('alert_iocs_association',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('ioc_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc.ioc_id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'ioc_id')
    )
    op.create_table('case_assets',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_name', sa.Text(), nullable=True),
    sa.Column('asset_description', sa.Text(), nullable=True),
    sa.Column('asset_domain', sa.Text(), nullable=True),
    sa.Column('asset_ip', sa.Text(), nullable=True),
    sa.Column('asset_external_ip', sa.Text(), nullable=True),
    sa.Column('asset_info', sa.Text(), nullable=True),
    sa.Column('asset_compromise_status_id', sa.Integer(), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('asset_tags', sa.Text(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('analysis_status_id', sa.Integer(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_enrichment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_status_id'], ['analysis_status.id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['assets_type.asset_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('case_graph_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['assets_type.asset_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_kanban',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('kanban_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_protagonist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_received_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('file_description', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('chain_of_custody', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['evidence_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_tags',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'tag_id'),
    sa.UniqueConstraint('case_id', 'tag_id', name='case_tags_case_id_tag_id_key')
    )
    op.create_index(op.f('ix_case_tags_tag_id'), 'case_tags', ['tag_id'], unique=False)
    op.create_table('case_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_title', sa.Text(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_tags', sa.Text(), nullable=True),
    sa.Column('task_open_date', sa.DateTime(), nullable=True),
    sa.Column('task_close_date', sa.DateTime(), nullable=True),
    sa.Column('task_last_update', sa.DateTime(), nullable=True),
    sa.Column('task_userid_open', sa.BigInteger(), nullable=True),
    sa.Column('task_userid_close', sa.BigInteger(), nullable=True),
    sa.Column('task_userid_update', sa.BigInteger(), nullable=True),
    sa.Column('task_status_id', sa.Integer(), nullable=True),
    sa.Column('task_case_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['task_status_id'], ['task_status.id'], ),
    sa.ForeignKeyConstraint(['task_userid_close'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_userid_open'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_userid_update'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases_assets_ext',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['assets_type.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('cases_events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_event_id', sa.BigInteger(), nullable=True),
    sa.Column('event_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('event_title', sa.Text(), nullable=True),
    sa.Column('event_source', sa.Text(), nullable=True),
    sa.Column('event_content', sa.Text(), nullable=True),
    sa.Column('event_raw', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_added', sa.DateTime(), nullable=True),
    sa.Column('event_in_graph', sa.Boolean(), nullable=True),
    sa.Column('event_in_summary', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('modification_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_color', sa.Text(), nullable=True),
    sa.Column('event_tags', sa.Text(), nullable=True),
    sa.Column('event_tz', sa.Text(), nullable=True),
    sa.Column('event_date_wtz', sa.DateTime(), nullable=True),
    sa.Column('event_is_flagged', sa.Boolean(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('event_id != parent_event_id', name='check_different_ids'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['parent_event_id'], ['cases_events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.Column('comment_update_date', sa.DateTime(), nullable=True),
    sa.Column('comment_user_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_case_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_alert_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['comment_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['comment_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('data_store_path',
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('path_uuid', sa.UUID(), nullable=True),
    sa.Column('path_name', sa.Text(), nullable=False),
    sa.Column('path_parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path_is_root', sa.Boolean(), nullable=True),
    sa.Column('path_case_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['path_case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('group_case_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('access_level', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc_link',
    sa.Column('ioc_link_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc.ioc_id'], ),
    sa.PrimaryKeyConstraint('ioc_link_id')
    )
    op.create_table('iris_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('report_title', sa.String(length=155), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('report_content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('note_directory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['note_directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes_group',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_title', sa.String(length=155), nullable=True),
    sa.Column('group_user', sa.BigInteger(), nullable=True),
    sa.Column('group_creationdate', sa.DateTime(), nullable=True),
    sa.Column('group_lastupdate', sa.DateTime(), nullable=True),
    sa.Column('group_case_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['group_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('object_state',
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('object_case_id', sa.BigInteger(), nullable=True),
    sa.Column('object_updated_by_id', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('object_state', sa.BigInteger(), nullable=True),
    sa.Column('object_last_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['object_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['object_updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('organisation_case_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('access_level', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similar_alerts_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_name', sa.Text(), nullable=True),
    sa.Column('ioc_value', sa.Text(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('ioc_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['asset_type_id'], ['assets_type.asset_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['ioc_type_id'], ['ioc_type.type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('activity_desc', sa.Text(), nullable=True),
    sa.Column('user_input', sa.Boolean(), nullable=True),
    sa.Column('is_from_api', sa.Boolean(), nullable=True),
    sa.Column('display_in_ui', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_case_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('access_level', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_case_effective_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('access_level', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_assets_association',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['case_assets.asset_id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'asset_id')
    )
    op.create_table('alert_similarity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('similar_alert_id', sa.BigInteger(), nullable=False),
    sa.Column('similarity_type', sa.String(length=255), nullable=True),
    sa.Column('matching_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('matching_ioc_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['matching_asset_id'], ['case_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['matching_ioc_id'], ['ioc.ioc_id'], ),
    sa.ForeignKeyConstraint(['similar_alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_asset_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_asset_id'], ['case_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_events_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['case_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['cases_events.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_events_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['event_category.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['cases_events.event_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('case_events_ioc',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('ioc_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['cases_events.event_id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc.ioc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_graph_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['dest_id'], ['case_graph_assets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['case_graph_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_store_file',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('file_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_original_name', sa.Text(), nullable=False),
    sa.Column('file_local_name', sa.Text(), nullable=False),
    sa.Column('file_description', sa.Text(), nullable=True),
    sa.Column('file_date_added', sa.DateTime(), nullable=True),
    sa.Column('file_tags', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_is_ioc', sa.Boolean(), nullable=True),
    sa.Column('file_is_evidence', sa.Boolean(), nullable=True),
    sa.Column('file_password', sa.Text(), nullable=True),
    sa.Column('file_parent_id', sa.BigInteger(), nullable=False),
    sa.Column('file_sha256', sa.Text(), nullable=True),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('file_case_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['file_parent_id'], ['data_store_path.path_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('event_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_event_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_event_id'], ['cases_events.event_id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_evidence_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_evidence_id'], ['case_received_file.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc_asset_link',
    sa.Column('ioc_asset_link_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['case_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc.ioc_id'], ),
    sa.PrimaryKeyConstraint('ioc_asset_link_id')
    )
    op.create_table('ioc_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_ioc_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['comment_ioc_id'], ['ioc.ioc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('note_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('note_title', sa.String(length=155), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('note_user', sa.BigInteger(), nullable=True),
    sa.Column('note_creationdate', sa.DateTime(), nullable=True),
    sa.Column('note_lastupdate', sa.DateTime(), nullable=True),
    sa.Column('note_case_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('directory_id', sa.BigInteger(), nullable=True),
    sa.Column('modification_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['note_directory.id'], ),
    sa.ForeignKeyConstraint(['note_case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['note_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('task_assignee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_task_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['comment_task_id'], ['case_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_note_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['comment_note_id'], ['notes.note_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_revisions',
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('note_title', sa.String(length=155), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('note_user', sa.BigInteger(), nullable=True),
    sa.Column('revision_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.ForeignKeyConstraint(['note_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('notes_group_link',
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('note_id', sa.BigInteger(), nullable=True),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['notes_group.group_id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes_group_link')
    op.drop_table('note_revisions')
    op.drop_table('note_comments')
    op.drop_table('task_comments')
    op.drop_table('task_assignee')
    op.drop_table('notes')
    op.drop_table('ioc_comments')
    op.drop_table('ioc_asset_link')
    op.drop_table('evidence_comments')
    op.drop_table('event_comments')
    op.drop_table('data_store_file')
    op.drop_table('case_graph_links')
    op.drop_table('case_events_ioc')
    op.drop_table('case_events_category')
    op.drop_table('case_events_assets')
    op.drop_table('asset_comments')
    op.drop_table('alert_similarity')
    op.drop_table('alert_assets_association')
    op.drop_table('user_case_effective_access')
    op.drop_table('user_case_access')
    op.drop_table('user_activity')
    op.drop_table('similar_alerts_cache')
    op.drop_table('organisation_case_access')
    op.drop_table('object_state')
    op.drop_table('notes_group')
    op.drop_table('note_directory')
    op.drop_table('iris_reports')
    op.drop_table('ioc_link')
    op.drop_table('group_case_access')
    op.drop_table('data_store_path')
    op.drop_table('comments')
    op.drop_table('cases_events')
    op.drop_table('cases_assets_ext')
    op.drop_table('case_tasks')
    op.drop_index(op.f('ix_case_tags_tag_id'), table_name='case_tags')
    op.drop_table('case_tags')
    op.drop_table('case_received_file')
    op.drop_table('case_protagonist')
    op.drop_table('case_kanban')
    op.drop_table('case_graph_assets')
    op.drop_table('case_assets')
    op.drop_table('alert_iocs_association')
    op.drop_index(op.f('ix_alert_case_association_case_id'), table_name='alert_case_association')
    op.drop_table('alert_case_association')
    op.drop_table('user_client')
    op.drop_table('iris_module_hooks')
    op.drop_table('contact')
    op.drop_table('cases')
    op.drop_table('alerts')
    op.drop_table('user_organisation')
    op.drop_table('user_group')
    op.drop_table('saved_filters')
    op.drop_table('iris_module')
    op.drop_table('ioc')
    op.drop_table('global_tasks')
    op.drop_table('evidence_type')
    op.drop_table('client')
    op.drop_table('case_template_report')
    op.drop_table('case_template')
    op.drop_table('case_classification')
    op.drop_table('users')
    op.drop_table('tlp')
    op.drop_table('task_status')
    op.drop_table('tags')
    op.drop_table('severities')
    op.drop_table('server_settings')
    op.drop_table('review_status')
    op.drop_table('report_type')
    op.drop_table('os_type')
    op.drop_table('organisations')
    op.drop_table('languages')
    op.drop_table('iris_hooks')
    op.drop_table('ioc_type')
    op.drop_table('groups')
    op.drop_table('event_category')
    op.drop_table('custom_attribute')
    op.drop_table('case_state')
    op.drop_table('assets_type')
    op.drop_table('analysis_status')
    op.drop_table('alert_status')
    op.drop_table('alert_resolution_status')
    # ### end Alembic commands ###
