"""regenerate indexes

Revision ID: da626af4a379
Revises: 7d805976d536
Create Date: 2026-04-21 12:30:53.090127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da626af4a379'
down_revision = '7d805976d536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_case_association_case_id'), 'alert_case_association', ['case_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_creation_time'), 'alerts', ['alert_creation_time'], unique=False)
    op.create_index(op.f('ix_alerts_alert_customer_id'), 'alerts', ['alert_customer_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_source_event_time'), 'alerts', ['alert_source_event_time'], unique=False)
    op.create_index(op.f('ix_alerts_alert_source_ref'), 'alerts', ['alert_source_ref'], unique=False)
    op.create_index(op.f('ix_alerts_alert_title'), 'alerts', ['alert_title'], unique=False)
    op.create_index(op.f('ix_case_assets_asset_domain'), 'case_assets', ['asset_domain'], unique=False)
    op.create_index(op.f('ix_case_assets_case_id'), 'case_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_assets_date_added'), 'case_assets', ['date_added'], unique=False)
    op.create_index(op.f('ix_case_assets_date_update'), 'case_assets', ['date_update'], unique=False)
    op.create_index(op.f('ix_case_tags_tag_id'), 'case_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_ioc_ioc_tags'), 'ioc', ['ioc_tags'], unique=False)
    op.execute(sa.text("CREATE INDEX idx_ioc_value_hash ON ioc (md5(ioc_value::text))"))
    op.alter_column('users', 'mfa_setup_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_setup_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_ioc_value_hash'), table_name='ioc')
    op.drop_index(op.f('ix_ioc_ioc_tags'), table_name='ioc')
    op.drop_index(op.f('ix_case_tags_tag_id'), table_name='case_tags')
    op.drop_index(op.f('ix_case_assets_date_update'), table_name='case_assets')
    op.drop_index(op.f('ix_case_assets_date_added'), table_name='case_assets')
    op.drop_index(op.f('ix_case_assets_case_id'), table_name='case_assets')
    op.drop_index(op.f('ix_case_assets_asset_domain'), table_name='case_assets')
    op.drop_index(op.f('ix_alerts_alert_title'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_source_ref'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_source_event_time'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_customer_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_creation_time'), table_name='alerts')
    op.drop_index(op.f('ix_alert_case_association_case_id'), table_name='alert_case_association')
    # ### end Alembic commands ###
